/*
 * error.h
 *
 *  Created on: 27 feb. 2022
 *      Author: Ludo
 */

#ifndef ERROR_H
#define ERROR_H

typedef enum {
	// Peripherals.
	ERROR_SOURCE_ADC,
	ERROR_SOURCE_AES,
	ERROR_SOURCE_FLASH,
	ERROR_SOURCE_I2C,
	ERROR_SOURCE_IWDG,
	ERROR_SOURCE_LPTIM,
	ERROR_SOURCE_LPUART,
	ERROR_SOURCE_NVM,
	ERROR_SOURCE_RCC,
	ERROR_SOURCE_RTC,
	ERROR_SOURCE_SPI,
	ERROR_SOURCE_TIM,
	ERROR_SOURCE_USART,
	// Utils.
	ERROR_SOURCE_MATH,
	ERROR_SOURCE_PARSER,
	ERROR_SOURCE_STRING,
	// Components.
	ERROR_SOURCE_DPS310,
	ERROR_SOURCE_MAX11136,
	ERROR_SOURCE_NEOM8N,
	ERROR_SOURCE_SHT3X,
	ERROR_SOURCE_SI1133,
	ERROR_SOURCE_SIGFOX,
	ERROR_SOURCE_SKY13317,
	ERROR_SOURCE_SX1232,
	ERROR_SOURCE_WIND,
	// Applicative
	ERROR_SOURCE_AT,
	// Last index.
	ERROR_SOURCE_LAST
} ERROR_source_t;

#endif /* ERROR_H */
