/*
 * error.h
 *
 *  Created on: 27 feb. 2022
 *      Author: Ludo
 */

#ifndef ERROR_H
#define ERROR_H

// Peripherals.
#include "adc.h"
#include "aes.h"
#include "flash.h"
#include "i2c.h"
#include "iwdg.h"
#include "lptim.h"
#include "lpuart.h"
#include "nvm.h"
#include "rcc.h"
#include "spi.h"
#include "rtc.h"
#include "tim.h"
#include "usart.h"
// Components.
#include "dps310.h"
#include "max11136.h"
#include "neom8n.h"
#include "sht3x.h"
#include "si1133.h"
#include "sx1232.h"
#include "wind.h"
// Utils.
#include "math.h"
#include "parser.h"
#include "string.h"

typedef enum {
	SPSWS_SUCCESS = 0,
	SPSWS_ERROR_BUSY,
	SPSWS_ERROR_SIGFOX_RC,
	// Peripherals.
	SPSWS_ERROR_BASE_ADC = 0x0100,
	SPSWS_ERROR_BASE_AES = (SPSWS_ERROR_BASE_ADC + ADC_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_FLASH = (SPSWS_ERROR_BASE_AES + AES_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_I2C = (SPSWS_ERROR_BASE_FLASH + FLASH_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_IWDG = (SPSWS_ERROR_BASE_I2C + I2C_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_LPTIM = (SPSWS_ERROR_BASE_IWDG + IWDG_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_LPUART = (SPSWS_ERROR_BASE_LPTIM + LPTIM_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_NVM = (SPSWS_ERROR_BASE_LPUART + LPUART_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_RCC = (SPSWS_ERROR_BASE_NVM + NVM_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_RTC = (SPSWS_ERROR_BASE_RCC + RCC_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_SPI = (SPSWS_ERROR_BASE_RTC + RTC_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_TIM = (SPSWS_ERROR_BASE_SPI + SPI_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_USART = (SPSWS_ERROR_BASE_TIM + TIM_ERROR_BASE_LAST),
	// Utils.
	SPSWS_ERROR_BASE_MATH = (SPSWS_ERROR_BASE_USART + USART_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_PARSER = (SPSWS_ERROR_BASE_MATH + MATH_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_STRING = (SPSWS_ERROR_BASE_PARSER + PARSER_ERROR_BASE_LAST),
	// Components.
	SPSWS_ERROR_BASE_DPS310 = (SPSWS_ERROR_BASE_STRING + STRING_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_MAX11136 = (SPSWS_ERROR_BASE_DPS310 + DPS310_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_NEOM8N = (SPSWS_ERROR_BASE_MAX11136 + MAX11136_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_SHT3X = (SPSWS_ERROR_BASE_NEOM8N + NEOM8N_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_SI1133 = (SPSWS_ERROR_BASE_SHT3X + SHT3X_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_SX1232 = (SPSWS_ERROR_BASE_SI1133 + SI1133_ERROR_BASE_LAST),
	SPSWS_ERROR_BASE_WIND = (SPSWS_ERROR_BASE_SX1232 + SX1232_ERROR_BASE_LAST),
	// Libraries.
	SPSWS_ERROR_BASE_SIGFOX = (SPSWS_ERROR_BASE_WIND + WIND_ERROR_BASE_LAST),
	// Last index.
	SPSWS_ERROR_BASE_LAST
} SPSWS_status_t;

#endif /* ERROR_H */
