/*
 * embedded_utils_flags.h
 *
 *  Created on: 15 aug. 2024
 *      Author: Ludo
 */

#ifndef __EMBEDDED_UTILS_FLAGS_H__
#define __EMBEDDED_UTILS_FLAGS_H__

#include "spsws_flags.h"
#include "usart.h"
#include "version.h"

/*** Embedded utility functions compilation flags ***/

#define EMBEDDED_UTILS_HW_INTERFACE_ERROR_BASE_LAST     USART_ERROR_BASE_LAST

#define EMBEDDED_UTILS_TERMINAL_INSTANCES_NUMBER        1
#define EMBEDDED_UTILS_TERMINAL_BUFFER_SIZE             64

#define EMBEDDED_UTILS_AT_INSTANCES_NUMBER              1
#define EMBEDDED_UTILS_AT_INTERNAL_COMMANDS_ENABLE
#define EMBEDDED_UTILS_AT_COMMANDS_LIST_SIZE            32
#define EMBEDDED_UTILS_AT_BUFFER_SIZE                   64
#ifdef EMBEDDED_UTILS_AT_INTERNAL_COMMANDS_ENABLE
#define EMBEDDED_UTILS_AT_SW_VERSION_MAJOR              GIT_MAJOR_VERSION
#define EMBEDDED_UTILS_AT_SW_VERSION_MINOR              GIT_MINOR_VERSION
#define EMBEDDED_UTILS_AT_SW_VERSION_INDEX              GIT_COMMIT_INDEX
#define EMBEDDED_UTILS_AT_SW_VERSION_DIRTY_FLAG         GIT_DIRTY_FLAG
#define EMBEDDED_UTILS_AT_SW_VERSION_ID                 GIT_COMMIT_ID
#endif

#define EMBEDDED_UTILS_ERROR_STACK_DEPTH                32
#define EMBEDDED_UTILS_ERROR_STACK_SUCCESS_VALUE        0
#define EMBEDDED_UTILS_ERROR_STACK_SIGFOX

//#define EMBEDDED_UTILS_STRING_HEXADECIMAL_UPPER_CASE

#ifdef HW1_0
#define EMBEDDED_UTILS_MATH_PRECISION                   0
#endif
#ifdef HW2_0
#define EMBEDDED_UTILS_MATH_PRECISION                   1
#endif
#ifdef SPSWS_WIND_RAINFALL_MEASUREMENTS
#define EMBEDDED_UTILS_MATH_COS_TABLE
#define EMBEDDED_UTILS_MATH_SIN_TABLE
#define EMBEDDED_UTILS_MATH_ATAN2
#endif

#endif /* __EMBEDDED_UTILS_FLAGS_H__ */
